name: Telegram text message
description: Action sends text message to telegram using bot
inputs:
  message:
    description: Text to send
    required: true
  chat_id:
    description: Chat id where to send message
    required: true
  bot_token:
    description: Bot from which the message will be sent
    required: true
  disable_notification:
    description: Whether to disable notiffication or not
    required: false
    default: 'false'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ -z `which jq 2>/dev/null` ]; then sudo apt install -y jq ; fi
    - shell: bash
      run: |
        ./send.py -m "${{ inputs.message }}" \
          -c "${{ inputs.chat_id }}" \
          -t "${{ inputs.bot_token }}" \
          -d "${{ inputs.disable_notification }}"
