name: Telegram text message
description: Action sends text message to telegram using bot
inputs:
  message:
    description: Text to send
    required: true
    default: TODO
  chat_id:
    description: Chat id where to send message
    required: true
  bot_token:
    description: Bot from which the message will be sent
    required: true
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        if [ -z `which jq 2>/dev/null` ]; then sudo apt install -y jq ; fi
    - shell: bash
      run: |
        answer=`curl -X POST \
          -H 'Content-Type: application/json' \
          -d "{\"chat_id\": \"${{ inputs.chat_id }}\" , \"text\": \"${{ inputs.message }}\" , \"disable_notification\": false}" \
          "https://api.telegram.org/bot${{ inputs.bot_token }}/sendMessage"` ; \
        echo ; \
        result=`echo $answer | jq .ok`; \
        if [ $result == 'true' ]; then exit 0 ; else exit 1; fi

