name: Telegram text message
description: Action sends text message to telegram using bot
inputs:
  message:
    description: Text to send
    required: true
  chat_id:
    description: Chat id where to send message
    required: true
  bot_token:
    description: Bot from which the message will be sent
    required: true
  disable_notification:
    description: Whether to disable notiffication or not
    required: false
    default: 'false'
  disable_web_page_preview:
    description: Whether to disable url preview or not
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        ./send.py -m "${{ inputs.message }}" \
          -c "${{ inputs.chat_id }}" \
          -t "${{ inputs.bot_token }}" \
          -n "${{ inputs.disable_notification }}" \
          -p "${{ inputs.disable_web_page_preview }}"
